### ISSUE TITLE
Hopper and chest, and their minecart variants broken

### ISSUE THREAD

**Issue by RMEngelbrecht** [AxalotLDev/Async#10]
Async breaks the behaviour of hoppers/chests and their interaction with chests and hoppers.
Think: chest or hopper minecart above a hopper. Or a hopper minecart underneath a chest.
The initial sometimes works, but often stops working. The latter never works.

No errors or anything in the logs, so it's just how the mod works rn.

**Comment by FurryMileon** [comment]
> Async breaks the behaviour of hoppers/chests and their interaction with chests and hoppers. Think: chest or hopper minecart above a hopper. Or a hopper minecart underneath a chest. The initial sometimes works, but often stops working. The latter never works.
> 
> No errors or anything in the logs, so it's just how the mod works rn.

There are two possible reasons for this problem:
1) It's happening due to asynchronous entity processing.
2) It's occurring because the item pickup method has been moved to synchronous processing. We did this because parallel processing was causing item duplication (duping).

**Comment by AxalotLDev** [comment]
Temporarily disable parallel processing for hopper minecarts

**Comment by RMEngelbrecht** [comment]
@AxalotLDev Sorry for the stupid question, but is that something I need to do or you guys do?
And if I need to: how do I do it for only minecarts?

**Comment by FurryMileon** [comment]
> @AxalotLDev Sorry for the stupid question, but is that something I need to do or you guys do? And if I need to: how do I do it for only minecarts?


Don't worry about it, he was just testing the integration between GitHub and Discord.

**Comment by FurryMileon** [comment]
> @AxalotLDev Sorry for the stupid question, but is that something I need to do or you guys do?
And if I need to: how do I do it for only minecarts?

We'll be releasing a version with a fix for this issue soon.

**Comment by RMEngelbrecht** [comment]
Okay amazing, as always thank you guys for the hard work! Спасибо!

**Comment by FurryMileon** [comment]
> Okay amazing, as always thank you guys for the hard work! Спасибо!

Try this version
[async-0.1.0+rc8-1.21.1.zip](https://github.com/user-attachments/files/17447405/async-0.1.0%2Brc8-1.21.1.zip)

**Comment by RMEngelbrecht** [comment]
@FurryMileon Can confirm hopper functionality is completely restored again!
