### ISSUE TITLE
Я вот не знаю, но очень похож на русского разработчика))

### ISSUE THREAD

**Issue by kitovoi111** [AxalotLDev/Async#11]
Только русский братушка мог написать в описании к моду MODERfix ))

**Comment by wicivo** [comment]
> Только русский братушка мог написать в описании к моду MODERfix ))

да, разрабы русские

**Comment by FurryMileon** [comment]
> > Только русский братушка мог написать в описании к моду MODERfix ))
> 
> да, разрабы русские

акс не хочет быть русским )

**Comment by FurryMileon** [comment]
> Только русский братушка мог написать в описании к моду MODERfix ))

а это моя оплошность XD )

**Comment by kitovoi111** [comment]
Молодцы, что решили взяться за мультипоточность сущностей, это была самая главная проблема оптимизации, теперь хотя бы можно делать сервер на фабрике спокойно.

**Comment by xbxct** [comment]
чё даже перевоить не надо? получается я зря перегонял через переводчик.

**Comment by kitovoi111** [comment]
> чё даже перевоить не надо? получается я зря перегонял через переводчик.

)))
