### ISSUE TITLE
Server crashes after starting

### ISSUE THREAD

**Issue by pewblaze** [AxalotLDev/Async#14]
Hi my server crashes after starting the world with this mod. 
Crash Report:
https://gist.github.com/pewblaze/5e926e5b4fb35eeb2a1ecefb2b582c4f

Latest Log:
https://gist.github.com/pewblaze/03411baae69c93f2432b69ef894197ec

**Comment by FurryMileon** [comment]
> Hi my server crashes after starting the world with this mod. Crash Report: https://gist.github.com/pewblaze/5e926e5b4fb35eeb2a1ecefb2b582c4f
> 
> Latest Log: https://gist.github.com/pewblaze/03411baae69c93f2432b69ef894197ec



Try the latest version
https://modrinth.com/mod/async/version/0.1.1+alpha.2-1.21.1
