### ISSUE TITLE
Server crash 1.21.1 fabric

### ISSUE THREAD

**Issue by kitovoi111** [AxalotLDev/Async#16]
[crash-2024-10-27_13.38.50-server.txt](https://github.com/user-attachments/files/17534124/crash-2024-10-27_13.38.50-server.txt)

**Comment by kitovoi111** [comment]
[2024-10-27-1.log](https://github.com/user-attachments/files/17534126/2024-10-27-1.log)

**Comment by suerion** [comment]
Had also an crash on tick entity
https://mclo.gs/Odlju52

**Comment by kitovoi111** [comment]
[crash-2024-10-27_13.56.55-server.txt](https://github.com/user-attachments/files/17534968/crash-2024-10-27_13.56.55-server.txt)
New crash

**Comment by kitovoi111** [comment]
[2024-10-27-2.log](https://github.com/user-attachments/files/17534971/2024-10-27-2.log)
log

**Comment by AxalotLDev** [comment]
Try the new version alpha 5 and send logs if the error remains

**Comment by kitovoi111** [comment]
> Try the new version alpha 5 and send logs if the error remains

[crash-2024-10-27_19.02.33-server.txt](https://github.com/user-attachments/files/17557132/crash-2024-10-27_19.02.33-server.txt)
[crash-2024-10-27_21.06.56-server.txt](https://github.com/user-attachments/files/17557133/crash-2024-10-27_21.06.56-server.txt)
Брат чекай, еще 2 краша какие то интересные, но это все еще на старой версии

**Comment by AxalotLDev** [comment]
> > Try the new version alpha 5 and send logs if the error remains
> 
> [crash-2024-10-27_19.02.33-server.txt](https://github.com/user-attachments/files/17557132/crash-2024-10-27_19.02.33-server.txt) [crash-2024-10-27_21.06.56-server.txt](https://github.com/user-attachments/files/17557133/crash-2024-10-27_21.06.56-server.txt) Брат чекай, еще 2 краша какие то интересные, но это все еще на старой версии

Can you write how to reproduce?

**Comment by kitovoi111** [comment]
> > > Try the new version alpha 5 and send logs if the error remains
> > 
> > 
> > [crash-2024-10-27_19.02.33-server.txt](https://github.com/user-attachments/files/17557132/crash-2024-10-27_19.02.33-server.txt) [crash-2024-10-27_21.06.56-server.txt](https://github.com/user-attachments/files/17557133/crash-2024-10-27_21.06.56-server.txt) Брат чекай, еще 2 краша какие то интересные, но это все еще на старой версии
> 
> Can you write how to reproduce?

Не в курсе ) Игроки играли - сервер сам по себе крашался, но щас новую версию закинул, посмотрим че будет

**Comment by AxalotLDev** [comment]
Ok, try new version

**Comment by suerion** [comment]
[crash-2024-10-30_22.28.11-server.txt](https://github.com/user-attachments/files/17580031/crash-2024-10-30_22.28.11-server.txt)


New crash on my side, with latest version

**Comment by suerion** [comment]
https://mclo.gs/e4GYqdw

Had again an Watchdog issue 

I had nothing done, only looked on configs,

@AxalotLDev

**Comment by AxalotLDev** [comment]
Try increasing the max-tick-time value in the server.properties file

**Comment by suerion** [comment]
Server runs yet with 180.000 will look later, if it crashed again

**Comment by AxalotLDev** [comment]
> Server runs yet with 180.000 will look later, if it crashed again

Sorry, I found a mistake, I'll fix it soon

**Comment by AxalotLDev** [comment]
try https://modrinth.com/mod/async/version/0.1.2+alpha.2-1.21.1

**Comment by FurryMileon** [comment]
It should be fixed in the new version of the mod.
