### ISSUE TITLE
Beacon effect issues with players

### ISSUE THREAD

**Issue by RMEngelbrecht** [AxalotLDev/Async#17]
Beacon effects seem to get stuck on players (without the game realising it). Mainly speed gets stuck, without the effect showing in the HUD.

Very easy to replicate by going through a portal while having the beacon effect applied.

No logs right now, but will try to get it later.

**Comment by AxalotLDev** [comment]
The mod should not affect players. Waiting for the log.

**Comment by RMEngelbrecht** [comment]
Apologies, misattributed this to Async.
