### ISSUE TITLE
(OFFTOP) Небольшой вопрос по поводу 1.19.2 мультипотока (Forge)

### ISSUE THREAD

**Issue by kitovoi111** [AxalotLDev/Async#21]
Общался я когда-то с хорошим разработчиком, портирует моды, смог портануть MCMT на Forge 1.19.2

https://github.com/min2222/MCMTForge - но имеется куча ошибок и краши, то мир не сохраняется после команды /stop сервера и всякая ерундовина, сколько не пытался починить - моих знании не хватает, можете как нибудь помочь и добавить поддержку? А то основные моды глобальные на 1.19.2 щас в основном (IC2 Classic, Create) и прочие. Был бы неприменно благодарен, вот прям сильно не хватает именно мультипотока.

**Comment by kitovoi111** [comment]
Мод сам по себе вроде бы реально работает, но есть рандомные краши, было бы круто если бы Вы смогли его запустить с модом https://legacy.curseforge.com/minecraft/mc-mods/ic2-classic - это было бы легендарно.

(запускаться то он запускается с модами, но когда я подключаю колоссальный механизм и появляются трубы, то некоторые механизмы перестают работать, а трубы спамят ошибками в консоли), а если даже без модов мультипоток запускать, то он через какое то время просто сервер крашает и все. Зависает.

**Comment by AxalotLDev** [comment]
At the moment we are finalizing the mod so that there are no critical errors. I think that it is necessary to port it to other loaders when the finalization is completed. Unfortunately I can't help yet.
