### ISSUE TITLE
[Suggestion] Please add support version 1.19.2 Forge

### ISSUE THREAD

**Issue by kitovoi111** [AxalotLDev/Async#23]
I will help check and perfect multithreading for Forge 1.19.2

I have a server with 100+ online.

Mods that need to be added to the list of supported: Canary, ModernFix, IC2 Classic.

**Comment by wicivo** [comment]
you've already been answered that question

**Comment by wicivo** [comment]
As soon as all critical bugs will be fixed maybe the mod author will make a port to NeoForge, but I don't think 1.19.2 will be affected

**Comment by wicivo** [comment]
https://github.com/AxalotLDev/Async/issues/21#issuecomment-2456461092
