### ISSUE TITLE
Странное поведение TPS (fabric 1.21.1)

### ISSUE THREAD

**Issue by kitovoi111** [AxalotLDev/Async#24]
И так, значит, загрузил я моды 

Async
Lithium
ModernFix
C2ME
Chunky

Сделал карту 
/worldborder center 0 0
/worldborder set 4000

Далее прогрузил её

/chunky world world
/chunky radius 2000
/cnunky start

После этого решил загнать ботов, с /gamerule spawnradius 2000 (чтобы они были автоматически раскиданы по миру)

Как только боты заходят, появляются подвисания сервера и TPS тупо падает до 5-8, когда загружено около 50-60 ботов.
Убрал мод C2ME - лаги вроде бы поушли при подключении ботов, но TPS все так же оказывался на дне и лагал сервер.

Чтобы Вы понимали, я раньше делал все тоже самое, только без мода Async, а стоял мод VMP и TTS20 и я мог спокойно нагрузить на сервере около 400-500 ботов на 18-20 тпс.

Данные тачки:

IntelCore i9-12900K
64GB RAM
NVME 1TB

Выделено на сервер было 32гб ОЗУ. (до этого все тоже самое делал без мода Async, спокойно без зависании загонял 400-600 ботов раскиданных по миру)

**Comment by kitovoi111** [comment]
Где то просчитался, но где? Почему тпсу так плохо стало вдруг. Вроде бы с мультипотоком я должен при этом условии около 500-600 игроков спокойно без проблем тянуть, раз мультипоток сущностей имеется, но вот что-то идет не так. Причина тряски TPS?

**Comment by wicivo** [comment]
Что за боты?

**Comment by kitovoi111** [comment]
https://disk.yandex.ru/d/CXMBqiBrCEM4Bw

**Comment by kitovoi111** [comment]
Вот стартер для ботов, в аргументах запуска все можно указать. Есть еще SoulFire, но он с фабриком не коннектится. Этот скрипт ботов от разраба MultiPaper/ShreddedPaper

**Comment by kitovoi111** [comment]
https://github.com/PureGero/minecraft-stress-test

**Comment by wicivo** [comment]
ща протестирую, какую версию Async использовал?

**Comment by kitovoi111** [comment]
> ща протестирую, какую версию Async использовал?

предпоследнюю Async 0.1.2+alpha.1-1.21.1

**Comment by kitovoi111** [comment]
![image](https://github.com/user-attachments/assets/e94ab099-aac1-4aa1-85bb-8d0d8ea6a5c2)
19 ботов, тпс падает в моменте, когда они подключаются, карта полностью груженная. MSPT тоже не нормальный.

**Comment by wicivo** [comment]
Может быть это из-за vmp?

**Comment by kitovoi111** [comment]
![image](https://github.com/user-attachments/assets/3cc79b38-e160-4894-a654-47ccfe19a7a9)

96 игроков, VMP не стоит мода.

**Comment by kitovoi111** [comment]
MSPT = 33.0 при 96 ботах на карте 1000х1000 раскиданные по всей карте. Такого не было раньше, тпс всегда был стабильно 20 даже при 300 ботах, но как поставил мод Async и убрал VMP, то тпсу плохо, от мультипотока смысла особо нету.

**Comment by wicivo** [comment]
У меня боты не могут зайти

**Comment by wicivo** [comment]
[Server thread/INFO]: com.mojang.authlib.GameProfile@26db37a3[id=cbe3dc37-cf50-36e1-b7a8-5a3772d18585,name=Bot232,properties={}] lost connection: Timed out

**Comment by kitovoi111** [comment]
> [Server thread/INFO]: com.mojang.authlib.GameProfile@26db37a3[id=cbe3dc37-cf50-36e1-b7a8-5a3772d18585,name=Bot232,properties={}] lost connection: Timed out

online-mode: false

**Comment by wicivo** [comment]
имеется

**Comment by kitovoi111** [comment]
И посмотри чтобы модов не было, например moonlight или прочих на серверной части, так как боты заходят с ванильного 1.21.1

**Comment by kitovoi111** [comment]
lost connection: Timed out - посмотри аргументы IP и PORT проверь правильность

**Comment by wicivo** [comment]
все правильно

**Comment by wicivo** [comment]
я подключаю их по 127.0.0.1:25565

**Comment by kitovoi111** [comment]
IP и PORT в разных аргументах должны быть, не вместе. Смотри чтобы моды на сервере были только оптимизационные не требующихся на стороне клиента

**Comment by wicivo** [comment]
короче проблема был в уровне сжатия

**Comment by FurryMileon** [comment]
Ну что поделать

**Comment by FurryMileon** [comment]
Совместимость с vmp придётся делать

**Comment by FurryMileon** [comment]
А без всех модов так же ?

**Comment by kitovoi111** [comment]
> А без всех модов так же ?

Без всех модов, не тестил. Но то что - точно тестил, это Lithium + VMP + ModernFix + C2ME + TTS20 + threadtweak +ScalableLux + Krypton + FerriteCore +ServerCore + Noisium + packetfixer = онии тянули около 500-600 ботов на 16-18 тпс, там уже чисто из за сущностей сервер не вывозил

По логике с Вашим мультипотоком, получится +- ShreddedPaper с модами. https://github.com/MultiPaper/ShreddedPaper
Очень мощное ядро, вот если бы фабрик на него, это была бы мечта.

**Comment by kitovoi111** [comment]
парни, чуть не по теме строчну сюда, если вы прям шарите за моддинг и в java шарите, напишите мне в тг @crackedlix - есть предложение одно хорошее для Вас (если по Forge)

**Comment by FurryMileon** [comment]
> > А без всех модов так же ?
> 
> Без всех модов, не тестил. Но то что - точно тестил, это Lithium + VMP + ModernFix + C2ME + TTS20 + threadtweak +ScalableLux + Krypton + FerriteCore +ServerCore + Noisium + packetfixer = онии тянули около 500-600 ботов на 16-18 тпс, там уже чисто из за сущностей сервер не вывозил
> 
> По логике с Вашим мультипотоком, получится +- ShreddedPaper с модами. https://github.com/MultiPaper/ShreddedPaper Очень мощное ядро, вот если бы фабрик на него, это была бы мечта.
[vmp-fabric-mc1.21.1-0.2.0+beta.7.169-all.zip](https://github.com/user-attachments/files/17651709/vmp-fabric-mc1.21.1-0.2.0%2Bbeta.7.169-all.zip)
на тестируй

**Comment by FurryMileon** [comment]
> > > А без всех модов так же ?
> > 
> > 
> > Без всех модов, не тестил. Но то что - точно тестил, это Lithium + VMP + ModernFix + C2ME + TTS20 + threadtweak +ScalableLux + Krypton + FerriteCore +ServerCore + Noisium + packetfixer = онии тянули около 500-600 ботов на 16-18 тпс, там уже чисто из за сущностей сервер не вывозил
> > По логике с Вашим мультипотоком, получится +- ShreddedPaper с модами. https://github.com/MultiPaper/ShreddedPaper Очень мощное ядро, вот если бы фабрик на него, это была бы мечта.
 
 
 [vmp-fabric-mc1.21.1-0.2.0+beta.7.169-all.zip](https://github.com/user-attachments/files/17651709/vmp-fabric-mc1.21.1-0.2.0%2Bbeta.7.169-all.zip)
 
 на тестируй

**Comment by FurryMileon** [comment]
> парни, чуть не по теме строчну сюда, если вы прям шарите за моддинг и в java шарите, напишите мне в тг @CrackedLix - есть предложение одно хорошее для Вас (если по Forge)


[async-0.1.3+alpha.1-1.21.1.zip](https://github.com/user-attachments/files/17651738/async-0.1.3%2Balpha.1-1.21.1.zip)
Попробуй по идеи должен теперь работать с VMP (нормально он будет работать или нет хз скидывай ошибки и уж тем более краши попытаемся исправить их)

**Comment by FurryMileon** [comment]
> парни, чуть не по теме строчну сюда, если вы прям шарите за моддинг и в java шарите, напишите мне в тг @CrackedLix - есть предложение одно хорошее для Вас (если по Forge)

мы за фордж вообще  не шарим

**Comment by kitovoi111** [comment]
> > парни, чуть не по теме строчну сюда, если вы прям шарите за моддинг и в java шарите, напишите мне в тг @CrackedLix - есть предложение одно хорошее для Вас (если по Forge)
> 
> [async-0.1.3+alpha.1-1.21.1.zip](https://github.com/user-attachments/files/17651738/async-0.1.3%2Balpha.1-1.21.1.zip) Попробуй по идеи должен теперь работать с VMP (нормально он будет работать или нет хз скидывай ошибки и уж тем более краши попытаемся исправить их)

OK завтра потестирую братишка

**Comment by kitovoi111** [comment]
Стало намного лучше, но при 90 ботах MSPT = 30+ , что весьма странно.

**Comment by kitovoi111** [comment]
![image](https://github.com/user-attachments/assets/53cfc5d7-6f34-40df-be4f-1ccb4c7ca557)

**Comment by kitovoi111** [comment]
Очень странно. Такое ощущение мультипоток не работает на игроков. Нагрузка процесса сервера так и остается 15-18%, хотя по логике должна нагружаться с учетом мультипотока. Где-то ошибочка, ребят. Оптимизация мультипотока не работает должным образом на игроков.

**Comment by kitovoi111** [comment]
![image](https://github.com/user-attachments/assets/cc6fb2c8-d481-4a20-b14f-8813d3b3d043)
![image](https://github.com/user-attachments/assets/eed298cd-9b2b-47d6-aa0d-cd070b646a95)

**Comment by kitovoi111** [comment]
![image](https://github.com/user-attachments/assets/93a3022f-437c-45bc-a52d-529f9b984ee7)
160 ботов, тпс скачет, уже нестабильность.

**Comment by kitovoi111** [comment]
Так же я заметил, если выкинуть более 100 стаков булыжника не землю, это создат невероятные зависания тпс

**Comment by FurryMileon** [comment]
> Очень странно. Такое ощущение мультипоток не работает на игроков. Нагрузка процесса сервера так и остается 15-18%, хотя по логике должна нагружаться с учетом мультипотока. Где-то ошибочка, ребят. Оптимизация мультипотока не работает должным образом на игроков.

Приду домой попробую включить парарельную обработку игроков (сейчас она выключена потомучто вызывало некоторые баги, но вроде как я недавно её включал и всё было норм)

**Comment by AxalotLDev** [comment]
> Очень странно. Такое ощущение мультипоток не работает на игроков. Нагрузка процесса сервера так и остается 15-18%, хотя по логике должна нагружаться с учетом мультипотока. Где-то ошибочка, ребят. Оптимизация мультипотока не работает должным образом на игроков.

Async никак не оптимизирует игроков

**Comment by FurryMileon** [comment]
> ![image](https://private-user-images.githubusercontent.com/147491823/383784294-93a3022f-437c-45bc-a52d-529f9b984ee7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5ODkyODgsIm5iZiI6MTczMDk4ODk4OCwicGF0aCI6Ii8xNDc0OTE4MjMvMzgzNzg0Mjk0LTkzYTMwMjJmLTQzN2MtNDViYy1hNTJkLTUyOWY5Yjk4NGVlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwN1QxNDE2MjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NzBjNWU0NGFhMWI5MmZlYzNmZTk4ZjNkMTMwZGU4YmUyYjg4ODliODY1NjRmODRmODIzYTA2OWQzNGExZjM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.HLnSdIZrN5azl5jhuqCjgSxwbJnltc2ImECkuMIyefY) 160 ботов, тпс скачет, уже нестабильность.

попробуй эту версию

[async-0.1.3+alpha.1-1.21.1.zip](https://github.com/user-attachments/files/17662818/async-0.1.3%2Balpha.1-1.21.1.zip)

**Comment by FurryMileon** [comment]
> Так же я заметил, если выкинуть более 100 стаков булыжника не землю, это создат невероятные зависания тпс

у меня сервер выдерживает 3000 стаков булыжника, но если честно литиум оптимизирует итемы намного лучше чем мы (как минимум он не расходует на это ядра процессора), но проблема в том что если включить этот параметр что бы итемы были оптимизированы то сервер просто начнёт крашится так как этот параметр отвечает за все ентити колизии

**Comment by kitovoi111** [comment]
> > Так же я заметил, если выкинуть более 100 стаков булыжника не землю, это создат невероятные зависания тпс
> 
> у меня сервер выдерживает 3000 стаков булыжника, но если честно литиум оптимизирует итемы намного лучше чем мы (как минимум он не расходует на это ядра процессора), но проблема в том что если включить этот параметр что бы итемы были оптимизированы то сервер просто начнёт крашится так как этот параметр отвечает за все ентити колизии

интересно, а что то наподобие системы Folia fabric реально сделать?

**Comment by kitovoi111** [comment]
Типо не просто мультипоток там сущностей, тайлов и прочего, а именно региональный мультипоток, но мне кажется это надо фулл ядро переписывать, мод вряд ли такое осилит.

**Comment by FurryMileon** [comment]
> Типо не просто мультипоток там сущностей, тайлов и прочего, а именно региональный мультипоток, но мне кажется это надо фулл ядро переписывать, мод вряд ли такое осилит.

Ну технически это возможно, только если Folia меняет код самого ядра мы можем менять этот же код через Mixin (что мы и так делаем ибо по другому это не возможно)

**Comment by FurryMileon** [comment]
проблема в том что тогда скорей всего 90 % модов перестанут работать

**Comment by kitovoi111** [comment]
> проблема в том что тогда скорей всего 90 % модов перестанут работать

да тут не важно сколько модов перестанет работать, суть в том, что Вы будете первыми кто такую тему сделает. На фабрик и так модов по пальцам сосчитать, кому надо тот переделает моды под фольку.

Из основных тут Artifacts, Lootr, Waystones, Farmer's Delight вот самые адекватные моды на фабрик.

**Comment by kitovoi111** [comment]
> > Типо не просто мультипоток там сущностей, тайлов и прочего, а именно региональный мультипоток, но мне кажется это надо фулл ядро переписывать, мод вряд ли такое осилит.
> 
> Ну технически это возможно, только если Folia меняет код самого ядра мы можем менять этот же код через Mixin (что мы и так делаем ибо по другому это не возможно)

вот если бы Вы смогли сделать Folia Fabric модом, это было бы просто превосходно, тут я думаю скачивания пошли бы неимоверные под серверные части. Так как модовые сервера щас в полном дне по оптимизации, а на ванильный сервер онлайн набирать не так легко, да и держится он там пару дней, потом опять под ноль бежит. С модами куда интереснее, но с лимитом в 100 человек играть не так интересно, когда тпс зависит от общего потока, если кто-то решит сделать лаг ферму - страдать будут все, да и региональный мультипоток, как в фолии, намного лучше нежели обычный мультипоток (например как shreddedpaper)

**Comment by kitovoi111** [comment]
Когда Folia только вышла, везде вышли про это новости, на habr и прочих сайтах, всех волновал только один вопрос

"а с модами то работать будет?" :D

**Comment by FurryMileon** [comment]
> Когда Folia только вышла, везде вышли про это новости, на habr и прочих сайтах, всех волновал только один вопрос
> 
> "а с модами то работать будет?" :D

это в 100 раз труднее сделать чем все моды на оптимизацию фабрика

**Comment by FurryMileon** [comment]
> > Когда Folia только вышла, везде вышли про это новости, на habr и прочих сайтах, всех волновал только один вопрос
> > "а с модами то работать будет?" :D
> 
> это в 100 раз труднее сделать чем все моды на оптимизацию фабрика

У меня даже нет идей как тестировать такую систему

**Comment by FurryMileon** [comment]
> Когда Folia только вышла, везде вышли про это новости, на habr и прочих сайтах, всех волновал только один вопрос
> 
> "а с модами то работать будет?" :D

Ты лучше скажи что там с игроками в новой версии которую я скинул выше

**Comment by kitovoi111** [comment]
> Collaborator

буду тестить чуть позже, как только так сразу сообщу!

**Comment by kitovoi111** [comment]
Вот если бы для Forge 1.19.2 этот модик бы вы смогли перенести, это просто бы цены не было )) а то мой сервак от 100 онлайна уже из за сущностей умирает :C

**Comment by kitovoi111** [comment]
https://github.com/GoldenForge/GoldenForge вот такая штука есть на 1.19.2, но это ядро скорее смерть, чем в проде использовать, но там вроде как есть мультипоток сущностей, хотя мне кажется он там кривой до жопы

**Comment by kitovoi111** [comment]
Загрузил 200 ботов, и через servercore увеличил mob-cap в х2 раза, то есть сущностей стало в 2 раза больше. Такое ощущение, что есть мультипоток - что его нету, одно и тоже . 
![image](https://github.com/user-attachments/assets/9657159d-f0fc-426f-95bc-14028ae989cb)

**Comment by kitovoi111** [comment]
Ладно, не уделяйте щас этой проблеме особое значение. Возможно я где то просчитался, но не точно, я пока не могу прям сильно детальные тесты делать, так как фабрик 1.21 сервер еще сильно не планировал, так как ни модов на нем нету, если сравнивать по кол-ву контента Fabric или Vanilla, то все, что есть на фабрике легко переносится плагинами, те же Artifacts, которые действительно крутые. Многие сервера и проекты сейчас использую в основном 1.19.2-1.20.1 на Forge, все основные моды там, например на 1.19.2 Forge есть тот самый легендарный мод детства IC2 Classic, с которым играет весьма много игроков, тот же Alex's Caves имеет backport на 1.19.2, поэтому сейчас я уделяю почти все время 1.19.2, даже этого разработчика ishland (VMP, C2ME) хороший разработчик, молодец он, я попросил его портануть VMP на Forge, благодаря моей просьбе это произошло, он мне когда-то обещал и выполнил обещание ) Но вот сейчас вся суть проблемы оптимизации чисто мультипоток сущностей. Вот если бы его на 1.19.2 добавить, елки палки, это мечта.. Я сколько не пытался, и кого бы не просил, никто не смог, то ли знании недостаточно или просто мотивации не было этого делать. Вон тот MCMT 1.19.2 на Forge тоже по моей просьбе пробовали сделать, но не довели до ума, увы. Моя оптимизация сервера из разных модов и конфигурации спокойно держит на 20.00 TPS около 140 игроков, потом все падает, так как игроков много - сущностей еще больше становится, тем самым просто все на одном потоке стоит и не вывозит..

**Comment by kitovoi111** [comment]
Если бы Вы смогли сделать или довести до ума тот порт MCMT 1.19.2 Forge до рабочего состояния или бы перенести Ваш прекраснейший мод на 1.19.2 Forge, я бы смог Вам хоть ежедневно высылать отчеты или ошибки, по улучшению мода и оптимизации.

**Comment by FurryMileon** [comment]
> Загрузил 200 ботов, и через servercore увеличил mob-cap в х2 раза, то есть сущностей стало в 2 раза больше. Такое ощущение, что есть мультипоток - что его нету, одно и тоже . ![image](https://private-user-images.githubusercontent.com/147491823/384101463-9657159d-f0fc-426f-95bc-14028ae989cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEwMDY4NDUsIm5iZiI6MTczMTAwNjU0NSwicGF0aCI6Ii8xNDc0OTE4MjMvMzg0MTAxNDYzLTk2NTcxNTlkLWYwZmMtNDI2Zi05NWJjLTE0MDI4YWU5ODljYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwN1QxOTA5MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYWJhM2VhYWU3OTRlOWYzYzgyNGE2ZGYxYzJmMWMwYzAxOGU1OGM0ZjMxMzMyNDZjYTgxYzVhODE3MzgzZjljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5C0cAb--3lmnIT14CEoReLp8FUjCmsqjBiGgG4agEw4)

я короче посмотрел в чём был прикол (у себя на сервере) и понял что спавн система мобов то же хреново работает будем щас её решать

**Comment by FurryMileon** [comment]
> Если бы Вы смогли сделать или довести до ума тот порт MCMT 1.19.2 Forge до рабочего состояния или бы перенести Ваш прекраснейший мод на 1.19.2 Forge, я бы смог Вам хоть ежедневно высылать отчеты или ошибки, по улучшению мода и оптимизации.

да я хз как что то делать на фордже одно дело фабрик я бы просто взял и перенёс код на болею старую версию изменив некоторые штуки, а на фордже так не получится

**Comment by kitovoi111** [comment]
> > Если бы Вы смогли сделать или довести до ума тот порт MCMT 1.19.2 Forge до рабочего состояния или бы перенести Ваш прекраснейший мод на 1.19.2 Forge, я бы смог Вам хоть ежедневно высылать отчеты или ошибки, по улучшению мода и оптимизации.
> 
> да я хз как что то делать на фордже одно дело фабрик я бы просто взял и перенёс код на болею старую версию изменив некоторые штуки, а на фордже так не получится

так смотри, https://github.com/min2222/MCMTForge вот эта тема рабочая, но в ней ошибки, понять бы где они. Там сервер /stop не работает почему-то и через время сервак тупо замирает и не реагирует. В принципе этот мод работает с Canary, Modern Fix и прочими оптимизациями.

**Comment by kitovoi111** [comment]
А так это уже готовый мультипоток для Forge 1.19.2, вот бы его довести до ума и вообще конфетка была бы.

**Comment by kitovoi111** [comment]
> > Если бы Вы смогли сделать или довести до ума тот порт MCMT 1.19.2 Forge до рабочего состояния или бы перенести Ваш прекраснейший мод на 1.19.2 Forge, я бы смог Вам хоть ежедневно высылать отчеты или ошибки, по улучшению мода и оптимизации.
> 
> да я хз как что то делать на фордже одно дело фабрик я бы просто взял и перенёс код на болею старую версию изменив некоторые штуки, а на фордже так не получится

А так да, ты прав, перенести проще, нежели на фордже делать, Вы красавцы что сделали такую вещь, хоть кто то решился этим заняться. Но фабрик, к сожалению, имеет копеечное количество играбельных модов, в этом и беда. На форджак 1.19.2 если бы сделать, это было бы реально ГОДНО.

**Comment by wicivo** [comment]
https://youtu.be/uYFmiLzTwLc

**Comment by kitovoi111** [comment]
> https://youtu.be/uYFmiLzTwLc

Да, там смерть. У меня примерно так же, но с последней версией по лучше стало. Но все равно выше 200 уже смерть. Раньше без Async спокойно под 400-600 тянуло.

**Comment by kitovoi111** [comment]
Привет, ну как оно там? Не получилось починить?

**Comment by FurryMileon** [comment]
> Привет, ну как оно там? Не получилось починить?

попробуй новую версию

**Comment by FurryMileon** [comment]
возможно стало лучше, но не факт

**Comment by kitovoi111** [comment]
Пробовал, не помогло  (сейчас если релиз выкатали, не тестил) позже может.

**Comment by kitovoi111** [comment]
Ладно, не суть, я на Folia погнал ядро
