### ISSUE TITLE
Async mod doesnt load on game start

### ISSUE THREAD

**Issue by Mr-Squid42** [AxalotLDev/Async#25]
noticed that the newest version doesn't seem to load on game start.
it isn't shown in mod menu or in fabrics total loaded mod count.

minecraft 1.21.1
fabric 0.16.9
Async 0.1.3+alpha.1-1.21.1

**Comment by Mr-Squid42** [comment]
also happens in minecraft 1.21.3

**Comment by FurryMileon** [comment]
This mod is intended for server use only.

> also happens in minecraft 1.21.3
