### ISSUE TITLE
Все стало намного лучше. 300 ботов - 20 тпс, полет отличный.

### ISSUE THREAD

**Issue by kitovoi111** [AxalotLDev/Async#29]
Все стало намного лучше. 400 ботов - 20 тпс, полет отличный.

**Comment by kitovoi111** [comment]
![image](https://github.com/user-attachments/assets/2aab68c1-7d2c-428c-810d-6aac23eaa417)

**Comment by kitovoi111** [comment]
Отличная работа ОЛЕГ!

**Comment by kitovoi111** [comment]
https://spark.lucko.me/M7Qw8B9Djp - профайлер.
![image](https://github.com/user-attachments/assets/afa8abad-f5f1-48ab-a372-061a284b1204)
Карта тестирования 1000x1000 блоков.
Процессор: i9-12900K (8 core/16 threads)
RAM: 64GB/ 8GB RAM (выделено на сервер тестовый)
NVME 1TB

**Comment by kitovoi111** [comment]
![image](https://github.com/user-attachments/assets/78a92169-302a-483c-81ac-ccba5c8b8dd4)
странно только вот что, почему то нагрузка на ядра все равно не правильно отображается, всего 13% процессор забит, не знаю, в режиме простоя сервер бывает теряет TPS на несколько секунд, проверьте на локалке в чем проблема.

**Comment by FurryMileon** [comment]
> ![image](https://private-user-images.githubusercontent.com/147491823/390550169-78a92169-302a-483c-81ac-ccba5c8b8dd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3MzgxNjUsIm5iZiI6MTczMjczNzg2NSwicGF0aCI6Ii8xNDc0OTE4MjMvMzkwNTUwMTY5LTc4YTkyMTY5LTMwMmEtNDgzYy04MWFjLWNjYmE1YzhiOGRkNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyN1QyMDA0MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZWI2MWYzMzhhYjAyMDE3YmEyM2RjOWMyYmIyYmU4ZmQxZTU2YjIzZGU1ZTkxNjBmNzFlNDc3MzM0YjgxMDFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tK1HPy9mn3IE0d08oGzqQrhoTkCAmWBGWmBJUkTef14) странно только вот что, почему то нагрузка на ядра все равно не правильно отображается, всего 13% процессор забит, не знаю, в режиме простоя сервер бывает теряет TPS на несколько секунд, проверьте на локалке в чем проблема.

Ну скорей всего идёт упор именно в майнкрафтавскую часть кода, так как асинк способен задействовать +-24 ядра дальше уже сам майн начинает лагать и тут только переписывание кода майна поможет (что скорей всего приведёт к поломке механик и т.д.)

**Comment by kitovoi111** [comment]
tiles / projectiles / vehicles тоже в мультипоток идут?

**Comment by kitovoi111** [comment]
сделал карту 1500х1500 блоков и чего-то 400 ботов уже не вывезлось.
![image](https://github.com/user-attachments/assets/20af024c-9463-4e50-9ca6-e750c4798843)

**Comment by kitovoi111** [comment]
При 2к на 2к карте или больше,уже при 100 онлайна плохо дело.

**Comment by wicivo** [comment]
> сделал карту 1500х1500 блоков и чего-то 400 ботов уже не вывезлось. ![image](https://private-user-images.githubusercontent.com/147491823/390567994-20af024c-9463-4e50-9ca6-e750c4798843.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NTg0OTksIm5iZiI6MTczMjc1ODE5OSwicGF0aCI6Ii8xNDc0OTE4MjMvMzkwNTY3OTk0LTIwYWYwMjRjLTk0NjMtNGU1MC05Y2E2LWU3NTBjNDc5ODg0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQwMTQzMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYWY4MGMzYWRlMzVkMTcwYjc0MzIwNWFmMTJjZjc3OTFkMTA5N2I1NGQ0MWQwNTNmYTg1OGZiZWEzOTQ4OGEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5CiBmZMfN5REytJ6ZFMEKMgg_NzcJIn173Iz2YNiHng)

А без Async также?

**Comment by kitovoi111** [comment]
> > сделал карту 1500х1500 блоков и чего-то 400 ботов уже не вывезлось. ![image](https://private-user-images.githubusercontent.com/147491823/390567994-20af024c-9463-4e50-9ca6-e750c4798843.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3NTg0OTksIm5iZiI6MTczMjc1ODE5OSwicGF0aCI6Ii8xNDc0OTE4MjMvMzkwNTY3OTk0LTIwYWYwMjRjLTk0NjMtNGU1MC05Y2E2LWU3NTBjNDc5ODg0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQwMTQzMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYWY4MGMzYWRlMzVkMTcwYjc0MzIwNWFmMTJjZjc3OTFkMTA5N2I1NGQ0MWQwNTNmYTg1OGZiZWEzOTQ4OGEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5CiBmZMfN5REytJ6ZFMEKMgg_NzcJIn173Iz2YNiHng)
> 
> А без Async также?

не проверял, но раньше делал карту 2к на 2к, как помню, 600 спокойно вывозил.

UPD: проверил, без Async все куда хуже)) с Async все же лучше)

**Comment by kitovoi111** [comment]
Попробуйте на карте 5000х5000 размерами уместить не знаю ботов 300-400 на 20 тпс и без единого пролага, вот это будет уже успех.

**Comment by kitovoi111** [comment]
А то пока кроме ShreddedPaper (заброшено, увы) нет ядра, которое бы позволяло на небольшой карте иметь 400-500 онлайна. Фолия не подойдет, там нужна карта свыше 10к на 10к для 20 тпс.

**Comment by wicivo** [comment]
Ну получается проблему можно закрыть т.к. она решена

**Comment by FurryMileon** [comment]
> tiles / projectiles / vehicles тоже в мультипоток идут?

projectiles и vehicles в синхроне tile скорей всего парарельны (возможно мы выведен projectiles когда то в парарель, так как возможно баг который они вызывали был исправлен)
