### ISSUE TITLE
Thank you for your work!

### ISSUE THREAD

**Issue by kitovoi111** [AxalotLDev/Async#3]
A deep bow to you, for at least someone thought to make a multi-stream of entities, which was so lacking. But I did not understand how to disable mixins in c2me :D

**Comment by AxalotLDev** [comment]
Currently с2ьу not compatible, but can be fixed by interfering with mixins.
https://drive.google.com/file/d/1G3EO0Q-WHluALQkti4EqsSj7DlN2JriC/view?usp=sharing
Example c2me
