### ISSUE TITLE
Жители тормозят при сборе урожая

### ISSUE THREAD

**Issue by kitovoi111** [AxalotLDev/Async#30]
Парни, здаров. Не шарю, но кажись из за Async мода.

Как проверить:

Берем тепаемся в деревню к жителям и ищем грядку. Далее даем жителям профессию фермеров и выращиваем костной мукой у них посевы, далее смотрим как они их собирают. В одиночном мире (даже с модом SmarterFarmers сбор был очень быстрым) а вот когда я ставлю оптимизацию мод, то они как бы ломают посев - но он выпадает с задержкой причем такой рандомной.

**Comment by FurryMileon** [comment]
странно у меня всё нормально

**Comment by FurryMileon** [comment]
https://github.com/user-attachments/assets/82ae0ce7-87cd-4348-a9fc-33c1fb247205

**Comment by kitovoi111** [comment]
Понял. Буду искать ошибку в других оптимизационных модах.

**Comment by FurryMileon** [comment]
> Понял. Буду искать ошибку в других оптимизационных модах.

ну у меня вот так вот
![image](https://github.com/user-attachments/assets/25720300-8b9e-4722-b2ce-709cbb1f3a10)

**Comment by kitovoi111** [comment]
Кстати, гляньте моды оптимизации с legacy forge, там smoothchunk, limited chunk loading, chunk sending.

**Comment by kitovoi111** [comment]
там где то конфликт был в логах с cupboard зависимостью

**Comment by kitovoi111** [comment]
ThreadTweaks нужен для Async ? или лишний будет?

**Comment by kitovoi111** [comment]
![image](https://github.com/user-attachments/assets/994308eb-ff02-400f-881e-bcc53c948848)
Тут все же есть какой то прикол, когда житель подходит к компостнице, и пытается пополнить семена, ничего не происходит.

**Comment by kitovoi111** [comment]
![image](https://github.com/user-attachments/assets/20d5e1c2-61d9-4b57-9341-6b582ba3e5f2)
Они как были пустыми, так и остались. Хотя они подходят и закидывают туда семена.

**Comment by FurryMileon** [comment]
можешь кинуть сборку модов

**Comment by kitovoi111** [comment]
> можешь кинуть сборку модов

https://disk.yandex.ru/d/-K96Cm4BMhHu6A

**Comment by FurryMileon** [comment]
cupboard  мы не сможем исправить, так как у них код закрытый и скорей всего это им надо изменять у себя код исправить

**Comment by kitovoi111** [comment]
> cupboard мы не сможем исправить, так как у них код закрытый и скорей всего это им надо изменять у себя код исправить

не суть, там моды все равно сильного буста не дают. а что на счет жителей? почему коробки не заполняются эти?

**Comment by FurryMileon** [comment]
> cupboard мы не сможем исправить, так как у них код закрытый и скорей всего это им надо изменять у себя код



> ![image](https://private-user-images.githubusercontent.com/147491823/390890553-20d5e1c2-61d9-4b57-9341-6b582ba3e5f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MjM5MzksIm5iZiI6MTczMjgyMzYzOSwicGF0aCI6Ii8xNDc0OTE4MjMvMzkwODkwNTUzLTIwZDVlMWMyLTYxZDktNGI1Ny05MzQxLTZiNTgyYmEzZTVmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQxOTUzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNDgyMzY0ZTg4YjllOTlkZmRjMzEyYjVhYTA3NWQyMTFmMjUwY2UyMThlYTE5ZjZkZmYyMDg5MTNhYjBlODE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.i7SF-ApHU2OhKr8jou-Piwi1d3-Iaw5eClFS8MfTlT4) Они как были пустыми, так и остались. Хотя они подходят и закидывают туда семена.

а это кстати проблема где то в вашей сборке так как у меня они туда ничего не кладут даже без асинка

**Comment by kitovoi111** [comment]
> > cupboard мы не сможем исправить, так как у них код закрытый и скорей всего это им надо изменять у себя код
> 
> > ![image](https://private-user-images.githubusercontent.com/147491823/390890553-20d5e1c2-61d9-4b57-9341-6b582ba3e5f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MjM5MzksIm5iZiI6MTczMjgyMzYzOSwicGF0aCI6Ii8xNDc0OTE4MjMvMzkwODkwNTUzLTIwZDVlMWMyLTYxZDktNGI1Ny05MzQxLTZiNTgyYmEzZTVmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQxOTUzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNDgyMzY0ZTg4YjllOTlkZmRjMzEyYjVhYTA3NWQyMTFmMjUwY2UyMThlYTE5ZjZkZmYyMDg5MTNhYjBlODE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.i7SF-ApHU2OhKr8jou-Piwi1d3-Iaw5eClFS8MfTlT4) Они как были пустыми, так и остались. Хотя они подходят и закидывают туда семена.
> 
> а это кстати проблема где то в вашей сборке так как у меня они туда ничего не кладут даже без асинка

понял, значит мод SmarterFarmers тупит. В принципе проблему решил с задержкой.

**Comment by FurryMileon** [comment]
> > > cupboard мы не сможем исправить, так как у них код закрытый и скорей всего это им надо изменять у себя код
> > 
> > 
> > > ![image](https://private-user-images.githubusercontent.com/147491823/390890553-20d5e1c2-61d9-4b57-9341-6b582ba3e5f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MjM5MzksIm5iZiI6MTczMjgyMzYzOSwicGF0aCI6Ii8xNDc0OTE4MjMvMzkwODkwNTUzLTIwZDVlMWMyLTYxZDktNGI1Ny05MzQxLTZiNTgyYmEzZTVmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyOFQxOTUzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNDgyMzY0ZTg4YjllOTlkZmRjMzEyYjVhYTA3NWQyMTFmMjUwY2UyMThlYTE5ZjZkZmYyMDg5MTNhYjBlODE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.i7SF-ApHU2OhKr8jou-Piwi1d3-Iaw5eClFS8MfTlT4) Они как были пустыми, так и остались. Хотя они подходят и закидывают туда семена.
> > 
> > 
> > а это кстати проблема где то в вашей сборке так как у меня они туда ничего не кладут даже без асинка
> 
> понял, значит мод SmarterFarmers тупит. В принципе проблему решил с задержкой.

у меня они вообще не хотят класть что то в компостницу (даже без модов)
За всё время только один раз смог один житак тут что то сделать и всё

**Comment by FurryMileon** [comment]
![image](https://github.com/user-attachments/assets/7ebdbbb0-4ce4-4ba0-8a7b-ab129f254bcc)
походу баг майна (но это не точно)
