### ISSUE TITLE
Вопрос по оптимизации

### ISSUE THREAD

**Issue by kitovoi111** [AxalotLDev/Async#31]
https://spark.lucko.me/0ml1SeNYLR - карта 5000х5000, боты раскиданы неподвижно по всей карте на случайных координатах. Ботов: 133 игрока.

Оптимизация в ServerCore задействована на максимум, уменьшать mob-caps до 10% не хочется, мобов вообще не будет. Есть ли вариант как то еще бустануть оптимизацию?

Получается от силы 150 человек может вместить себя фабрик сервер. Хотелось бы чтобы человек 300-400 можно было бы вместить на карте 5000х5000 на 20 тпс стабильных и около 20-30 mspt.

![image](https://github.com/user-attachments/assets/699096f2-fde5-44b1-8ad9-e243a4b96d64)
![image](https://github.com/user-attachments/assets/38d96573-4ba9-4d7d-8b47-8621f40ca27c)
![image](https://github.com/user-attachments/assets/0dd91287-64a3-4015-ad2a-d483a022d1d6)

**Comment by FurryMileon** [comment]
мы не сможем это реализовать

**Comment by kitovoi111** [comment]
жаль.
