### ISSUE TITLE
CRASH SERVER FABRIC 1.21.1

### ISSUE THREAD

**Issue by kitovoi111** [AxalotLDev/Async#32]
Не прогрузил карту. Сделал 5000х5000 блоков, поставил рандомный спаун ботов по всей карты.

Каждые 10 секунд заходил +1 бот, в итоге то провисы при их появлении, в конце ваще крашнуло при наборе 50 ботов.
[crash-2024-11-29_17.23.31-server.txt](https://github.com/user-attachments/files/17962015/crash-2024-11-29_17.23.31-server.txt)

**Comment by kitovoi111** [comment]
[latest.log](https://github.com/user-attachments/files/17962017/latest.log)

**Comment by AxalotLDev** [comment]
попробуй установить max-tick-time=0

**Comment by kitovoi111** [comment]
> попробуй установить max-tick-time=0

в этом случае сервер не выбьет если он зависнет, проще 120 000 значение выставлять

**Comment by kitovoi111** [comment]
https://spark.lucko.me/2s8jXexMJu

**Comment by kitovoi111** [comment]
ModernFix 47.74%

**Comment by FurryMileon** [comment]
Там C2me умирает судя по ошибке
