### ISSUE TITLE
Парни 1.19.2 Forge пожалуйста сделайте)) моды все там основные, под IC2 Classic заточить бы и вообще мечта.

### ISSUE THREAD

**Issue by kitovoi111** [AxalotLDev/Async#33]
Парни 1.19.2 Forge пожалуйста сделайте)) моды все там основные, под IC2 Classic заточить бы и вообще мечта.

**Comment by kitovoi111** [comment]
Я не пойму откуда на фабрик людей цеплять, а вот на Forge под 200-300 онлайна сидит.

**Comment by kitovoi111** [comment]
Отчеты , сборку могу скинуть
За создание мультипотока - с меня $ донатами

**Comment by AxalotLDev** [comment]
Пока не в планах
