### ISSUE TITLE
[Error] Description: Chunk load failure `java.lang.ArrayIndexOutOfBoundsException:`

### ISSUE THREAD

**Issue by zndrmn** [AxalotLDev/Async#34]
I don't know what I did wrong but all of a sudden my chunks started to get thanos snapped out of existence (they seem to be fine after removing async. though I don't have many *useable* chunks in the first place)

This mod work fine in my other worlds but for some reason my semi-void world just had a heart attack with this mod.

https://mclo.gs/98PC07X

It also created a ton of chunk debug logs too if you need that.

**Comment by FurryMileon** [comment]
This issue is related to the new version of Lithium. Try installing an older version of Lithium:
https://modrinth.com/mod/lithium/version/mc1.21.1-0.13.1

**Comment by AxalotLDev** [comment]
Try use new realease

**Comment by zndrmn** [comment]
Will try it soon

**Comment by AxalotLDev** [comment]
Have you checked?

**Comment by zndrmn** [comment]
Sorry I forgor to test hehe. Everything seems to be working perfectly fine now! I'll open a new issue if I run into anything new

**Comment by zndrmn** [comment]
Uh oh it seems to be happening again. https://mclo.gs/z51WRIC

I think this happens after I restart/turn off(hibernate) my pc with the mod.

When I first installed it (on both occasions) it worked perfectly normal with no signs of any errors or anything. But after I turned on my pc and booted it up again, world errors started to occur again. I still haven't downgraded my lithium or anything, should I still be doing that?

yesterday I was working on my resource pack for like 6 hours with async installed and had zero errors. I even closed out of my game a couple of times too so yeahh.

**Comment by AxalotLDev** [comment]
[async-0.1.5+alpha.5-1.21.1.zip](https://github.com/user-attachments/files/18177769/async-0.1.5%2Balpha.5-1.21.1.zip)
Try this version

**Comment by zndrmn** [comment]
This time it broke after restarting the game. And also it was able to properly save(?) the world this time too. (didn't have to Alt F4 to close the game and didn't get stuck infinitely loading)

https://mclo.gs/w0vZNcw

**Comment by AxalotLDev** [comment]
[async-0.1.5+alpha.5-1.21.1.zip](https://github.com/user-attachments/files/18187124/async-0.1.5%2Balpha.5-1.21.1.zip)
Maybe this version

**Comment by zndrmn** [comment]
Okay, so far this is working (only opened and closed the game twice) but this time I'll wait a couple of days before closing the issue again.

**Comment by AxalotLDev** [comment]
[async.zip](https://github.com/user-attachments/files/18246808/async.zip)
Hello, could you test this version on your problem?

**Comment by zndrmn** [comment]
> Okay, so far this is working (only opened and closed the game twice) but this time I'll wait a couple of days before closing the issue again.

It seems like this build fixed the issue, after playing the game for many hours across multiple days I haven't run into the issue a single time

Oh (I'm curious) what was causing the issue in the first place? what fixed it?
