### ISSUE TITLE
Iron Golem spawn behavior

### ISSUE THREAD

**Issue by fdriessler** [AxalotLDev/Async#36]
When building Iron Golem Farms, using a design that should be capable of spawning up to 4 iron golems spawns ~8 or so.
My speculation as to what the reason is would be that several villagers have their panic calculated in seperate threads at the same time, resulting in all of them concluding that a new iron golem has to be spawned, rather than current vanilla behavior, where the first calculated villager spawns a iron golem and all following villagers just confirm the existence of one.
This also results in lower performance compared to running minecraft without Async installed A 16 Pod Iron Farm, 3 Villagers per Pod, Resulted in ~1.5-2 mspt with Async, ~0.8-1.1 mspt without Async.

This obviously results in iron farms producing at least 2x the amount of iron compared to vanilla and villages attacked by zombies generating a unnatural amount of iron golems.

**Comment by AxalotLDev** [comment]
Solved
