### ISSUE TITLE
Crashes with ViaFabric

### ISSUE THREAD

**Issue by taitan194** [AxalotLDev/Async#39]

**Comment by AxalotLDev** [comment]
Can you send me the logs?

**Comment by taitan194** [comment]
[latest.log](https://github.com/user-attachments/files/18259315/latest.log)

**Comment by taitan194** [comment]
![image](https://github.com/user-attachments/assets/63e6e841-c596-40ba-aeda-005a0c7e8132)

**Comment by AxalotLDev** [comment]
This is not an Async error. Try updating viafabric or rolling it back to the release version.
