### ISSUE TITLE
Make a Discord server

### ISSUE THREAD

**Issue by wicivo** [AxalotLDev/Async#7]
Make a Discord server

**Comment by FurryMileon** [comment]
> Make a Discord server

I'm working on it (might have a server today, I'm mostly waiting for Axolotl)

**Comment by wicivo** [comment]
I used to test MCMTFabric for maybe a year, but the author abandoned the project, and today I found this and I'm interested again, I can report bugs to you, but it will be more convenient for me to do it in Discord

**Comment by wicivo** [comment]
You're Russian, aren't you?

**Comment by FurryMileon** [comment]
> You're Russian, aren't you?

Да

**Comment by wicivo** [comment]
me too

**Comment by FurryMileon** [comment]
> me too

https://discord.gg/scvCQ2qKS3 
Заходи, будешь так сказать первым, если админов не считать XD
