### ISSUE TITLE
Ошибки

### ISSUE THREAD

**Issue by wicivo** [AxalotLDev/Async#9]
Я буду сюда кидать различные ошибки с которыми я столкнулся

https://mclo.gs/K9c3ZFm

**Comment by wicivo** [comment]
https://mclo.gs/3yBeAYJ
Это произошло когда я вернулся из незера(Это произошло рандомно и я не могу это воспроизвести)

rc6

**Comment by wicivo** [comment]
Мод  не работает для эллеев? 
![image](https://github.com/user-attachments/assets/ede57237-7f11-40e4-bfd3-16788766f88f)

**Comment by FurryMileon** [comment]
> Мод не работает для эллеев? ![image](https://private-user-images.githubusercontent.com/116191734/377904863-ede57237-7f11-40e4-bfd3-16788766f88f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyNjUzNDMsIm5iZiI6MTcyOTI2NTA0MywicGF0aCI6Ii8xMTYxOTE3MzQvMzc3OTA0ODYzLWVkZTU3MjM3LTdmMTEtNDBlNC1iZmQzLTE2Nzg4NzY2Zjg4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOFQxNTI0MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jM2ZiYjBlNDBmZWZlN2QwN2YyOTdkNmY0ZGQ1NzA4ZmMxM2NlMTFiMWY4YzJlNjEwZTM1NTlkZWQ4MWRkZWI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yeKk5FU0ZmmDcRq3bua8xx6DBJtX5g89G8XN5KfgD8M)

Да с ними есть один дюп и мы пока их вывели в синхрон, что бы они не дюпали предметы (так же с дильфинами и лисами, щас мы пытаемся устранить более критичные вещи потом займёмся исправлением дюпа)

**Comment by AxalotLDev** [comment]
WIP
